// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ces_Platform_Server_Side.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925194929__Adding_Teacher_Relations_of_Tests_and_Notes")]
    partial class _Adding_Teacher_Relations_of_Tests_and_Notes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.StudentInfoSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("StudentInfoId");

                    b.ToTable("StudentInfoSkill");
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.AuditableEntity", b =>
                {
                    b.HasBaseType("Ces_Platform_Server_Side.Models.Entity");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.Course", b =>
                {
                    b.HasBaseType("Ces_Platform_Server_Side.Models.AuditableEntity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.Note", b =>
                {
                    b.HasBaseType("Ces_Platform_Server_Side.Models.AuditableEntity");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.HasIndex("CourseId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("TeacherId");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.Report", b =>
                {
                    b.HasBaseType("Ces_Platform_Server_Side.Models.AuditableEntity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TItle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.Skill", b =>
                {
                    b.HasBaseType("Ces_Platform_Server_Side.Models.AuditableEntity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.Source", b =>
                {
                    b.HasBaseType("Ces_Platform_Server_Side.Models.AuditableEntity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StudentInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("StudentInfoId");

                    b.ToTable("Sources", (string)null);
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.StudentInfo", b =>
                {
                    b.HasBaseType("Ces_Platform_Server_Side.Models.AuditableEntity");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("StudentsInfos", (string)null);
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.Teacher", b =>
                {
                    b.HasBaseType("Ces_Platform_Server_Side.Models.AuditableEntity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("Teachers", (string)null);
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.Test", b =>
                {
                    b.HasBaseType("Ces_Platform_Server_Side.Models.AuditableEntity");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Tests", (string)null);
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.User", b =>
                {
                    b.HasBaseType("Ces_Platform_Server_Side.Models.AuditableEntity");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.StudentInfoSkill", b =>
                {
                    b.HasOne("Ces_Platform_Server_Side.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ces_Platform_Server_Side.Models.StudentInfo", "StudentInfo")
                        .WithMany("StudentInfoSkills")
                        .HasForeignKey("StudentInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("StudentInfo");
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.Note", b =>
                {
                    b.HasOne("Ces_Platform_Server_Side.Models.Course", "Course")
                        .WithMany("Notes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ces_Platform_Server_Side.Models.Teacher", "Teacher")
                        .WithMany("Notes")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.Source", b =>
                {
                    b.HasOne("Ces_Platform_Server_Side.Models.StudentInfo", "StudentInfo")
                        .WithMany("Sources")
                        .HasForeignKey("StudentInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentInfo");
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.Test", b =>
                {
                    b.HasOne("Ces_Platform_Server_Side.Models.Course", "Course")
                        .WithMany("Tests")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ces_Platform_Server_Side.Models.Teacher", "Teacher")
                        .WithMany("Tests")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.Course", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.StudentInfo", b =>
                {
                    b.Navigation("Sources");

                    b.Navigation("StudentInfoSkills");
                });

            modelBuilder.Entity("Ces_Platform_Server_Side.Models.Teacher", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
